name: JMeterAction
on:
 workflow_dispatch:
   inputs:
    targetconcurrency:
      type: string
      description: Target Concurrency
      required: true
    rampuptime:
      type: string
      description: Ramp Up Time
      required: true
    rampstepscount:
      type: string
      description: Ramp Steps Count
      required: true
    targetratetime:
      type: string
      description: Target Rate Time
      required: true
    thinktime:
      type: string
      description: Think Time
      required: true
   
            
jobs:
 test-action:
   runs-on: ubuntu-latest
   steps:
     - name: Cloning perfarchatomate repository
       uses: actions/checkout@main
       with:
           ref: pokeapi
     - name: Download dependencies
       run: |
             sudo apt-get install curl
             sudo apt-get install unzip
             sudo apt-get install tzdata
     - name: Preparing Environment
       run: |
             sudo mkdir -p /tmp/jmeter/
             sudo mkdir -p /home/jmeter/
             sudo curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz 
             sudo tar -xzf apache-jmeter-5.5.tgz
             sudo wget -O jpgc-casutg-2.10.zip https://jmeter-plugins.org/files/packages/jpgc-casutg-2.10.zip
             sudo unzip -o jpgc-casutg-2.10.zip -d /apache-jmeter-5.5/
             sudo pwd
     - name: Run JMeter Scenario
       run: sh /home/runner/work/perfarchautomate/perfarchautomate/apache-jmeter-5.5/bin/jmeter.sh -n -t /PokeAPI.jmx 
             -JTargetConcurrency=${{ inputs.targetconcurrency }} -JRampUpTime=${{ inputs.rampuptime }} -JRampStepsCount=${{ inputs.rampstepscount }}
             -JTargetRateTime=${{ inputs.targetratetime }} -JThinkTime=${{ inputs.thinktime }} -l /pokeapi.jtl
     - name: Generate HTML Report
       run: sh /apache-jmeter-5.5/bin/jmeter.sh -g pokeapi.jtl
            -o /reports/
     - name: Upload HTML Report
       uses: actions/upload-artifact@v1
       with:
         name: jmeter-test-results
         path: /reports/